services:
  db:
    image: postgres:15
    container_name: evsy-db
    restart: always
    environment:
      POSTGRES_USER: evsy
      POSTGRES_PASSWORD: evsy
      POSTGRES_DB: evsy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "evsy"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: evsy-backend
    restart: always
    env_file:
      - .env.example
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
    container_name: evsy-frontend
    restart: always
    env_file:
      - .env.example
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres_data:
