services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    command: >
      bash -c "alembic upgrade head && \
               uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    command: npm run dev

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 3s
      retries: 5
