services:
  backend:
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    command: >
      bash -c "alembic upgrade head && \
               uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
          VITE_API_URL: ${VITE_API_URL}
          VITE_ENV: ${VITE_ENV}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:5173
    env_file:
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: evsy
      POSTGRES_PASSWORD: evsy
      POSTGRES_DB: evsy
#    ports:
#      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'evsy']
      interval: 3s
      retries: 5
