databases:
  - name: evsy-db
    plan: free
    region: frankfurt

services:
  # BACKEND
  - name: evsy-backend
    type: web
    env: docker
    rootDir: backend
    plan: free
    autoDeploy: true
    region: frankfurt
    envVars:
      - key: ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: evsy-db
          property: connectionString
      - key: FRONTEND_URL
        fromService:
          type: web
          name: evsy
          property: serviceUrl

  # FRONTEND
  - name: evsy
    type: web
    env: docker
    rootDir: frontend
    plan: free
    autoDeploy: true
    region: frankfurt
    envVars:
      - key: VITE_ENV
        value: demo
      - key: VITE_API_URL
        fromService:
          type: web
          name: evsy-backend
          property: serviceUrl
      - key: __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS
        fromService:
          type: web
          name: evsy
          property: serviceUrl
      - key: VITE_LOG_LEVEL
        value: error
