"""add_performance_indexes

Revision ID: 8e1434cdf271
Revises: 23a12684fe55
Create Date: 2025-08-21 16:44:46.132403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1434cdf271'
down_revision: Union[str, None] = '23a12684fe55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_index('idx_fields_field_type', 'fields', ['field_type'])
    op.create_index('idx_event_tags_tag_id', 'event_tags', ['tag_id'])
    op.create_index('idx_event_tags_event_id', 'event_tags', ['event_id'])
    op.create_index('idx_event_fields_field_id', 'event_fields', ['field_id'])
    op.create_index('idx_event_fields_event_id', 'event_fields', ['event_id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('idx_event_fields_event_id')
    op.drop_index('idx_event_fields_field_id')
    op.drop_index('idx_event_tags_event_id')
    op.drop_index('idx_event_tags_tag_id')
    op.drop_index('idx_fields_field_type')
    
    # ### end Alembic commands ###
